# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Blog of Random Things"
description: >
   Blog of Random Things

email: shen.marshall@gmail.com
#blog logo
logo: "assets/images/conway_square.png"
ico: "assets/images/conway.ico"
# blog cover
cover: "assets/images/conway.jpg"

name: 'Marshall Shen'
author: 'Marshall Shen'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.getconway.com"
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/marshallshen
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
